[package]
name = "bevy_ui_builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy-ui-navigation = "0.28.0"
bevy_eventlistener = "0.2.2"
dark-light = "1.0.0"
once_cell = "1.18.0"

[dependencies.bevy]
version = "0.11.0"
default-features = false
features = ["bevy_ui", "bevy_text", "bevy_winit"]

[target.'cfg(target_os = "linux")'.dependencies.bevy]
version = "0.11.0"
default-features = false
features = ["x11", "wayland"]
