[package]
name = "bevy_ui_builder"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"


[dependencies]
bevy-ui-navigation = "0.33.1"
ahash = "0.7.8" # Workaround for some rust nightly issue, we don't actually care about ahash
dark-light = "1.0.0"
once_cell = "1.18.0"
trees = "0.4.2"

[dependencies.bevy]
version = "0.12.1"
default-features = false
features = ["bevy_ui", "bevy_text", "bevy_winit", "default_font"]

[target.'cfg(target_os = "linux")'.dependencies.bevy]
version = "0.12.1"
default-features = false
# TODO! Please re-add Wayland when it is fixed in Bevy
features = ["x11"]
