[package]
name = "bevy_ui_builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
dark-light = "1.0.0"
once_cell = "1.18.0"
